riot:
  api:
    url: https://kr.api.riotgames.com
    key: RGAPI-8f81a5fd-f3f8-49b7-8db2-2ea0c30227d0

logging:
  level:
    com:
      example:
        openfeign: DEBUG

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            dismiss404: true