riot:
  api:
    url: https://kr.api.riotgames.com
    key: ${RIOT_API_KEY}

logging:
  level:
    com:
      example:
        openfeign: DEBUG

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            dismiss404: true